apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress
  namespace: wordpress
spec:
  rules:
  - host: wordpress.itvcloud.nl
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 80

